### ISSUE TITLE
Problem sub menu not showing

### ISSUE THREAD

**Issue by agusmakmun** [rossp/django-menu#13]
Hello there, i was using this django-menu for my project, but we have some problem if we need to show sub-menu item.
Now we use django 1.8.5

```
<ul class="nav navbar-nav">
{% load menubuilder %}
{% menu headernavigation %}
  {% for item in menuitems %}
    <li>
      <a href="{{ item.url }}" title="{{ item.title|escape }}"{% if item.current %} class='current active'{% endif %}>{{ item.title }}</a>
      {% if submenu_items %}
        <ul>
          {% for submenu_items in submenu_items %}
              <li>{{ submenu_items }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    </li>
  {% endfor %}
</ul>
```

I was try wollowing tutorial from: https://www.rossp.org/blog/menus/, but not showing...

```
{% load menubuilder %}
{% submenu %}
{% if submenu %}
  {{ submenu.name }}
  {% for item in submenu_items %}
    {{ item.title }}
  {% endfor %}
{% endif %}
```

**Comment by rossp** [comment]
What happens when you try? Anything in your shell / log output? Do any of your menus or submenus work? What's your data look like? What URL are you calling `submenu` on? I'm going to need a bit more info to help out here but not sure I'll be able to fix your problem given the age of this code, sorry.

**Comment by agusmakmun** [comment]
Thank you so much for your fast response..

my problem is fail to display the sub-menu..
previously I have done some experiments to be able to display the sub-menu.
This is my menu settings dashboard.
![1](https://cloud.githubusercontent.com/assets/7134451/11298155/b1782c1a-8faf-11e5-9645-b35c6c99547a.png)

we found `context['submenu_items']` in the file of `menubuilder.py`:
```
def build_sub_menu(parser, token):
    """
    {% submenu %}
    """
    return SubMenuObject()

class SubMenuObject(template.Node):
    def __init__(self):
        pass

    def render(self, context):
        current_path = context['request'].path
        user = context['request'].user
        menu = False
        for m in Menu.objects.filter(base_url__isnull=False):
            if m.base_url and current_path.startswith(m.base_url):
                menu = m

        if menu:
            context['submenu_items'] = get_items(menu.slug, current_path, user)
            context['submenu'] = menu
        else:
            context['submenu_items'] = context['submenu'] = None
        return ''
```

So if we try this to show it, but not showing at all.
```
{% load menubuilder %}
{% submenu %}
{% if submenu %}
  {{ submenu.name }}
  {% for item in submenu_items %}
    {{ item.title }}
  {% endfor %}
{% endif %}
```
This is results of it:
![menus](https://cloud.githubusercontent.com/assets/7134451/11298308/8e04ebdc-8fb0-11e5-95ac-e2113a6a8e12.png)

But if we try this:
```
<ul class="nav navbar-nav">{% load menubuilder %}
{% menu headernavigation %}
  {% for item in menuitems %}
    <li>
      <a href="{{ item.url }}" title="{{ item.title|escape }}"{% if item.current %} class='current active'{% endif %}>{{ item.title }}</a>
      {% if submenu_items %}
        <ul>
          {% for submenu_items in submenu_items %}
              <li>{{ submenu_items }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    </li>
  {% endfor %}
</ul>
```

Some main menu is show all, like this picture:
![menus1](https://cloud.githubusercontent.com/assets/7134451/11298352/e09bff20-8fb0-11e5-9de8-d523d5d7fb5c.png)

but why that sub-menu became the main menu?
we verry confused to solved this problem, help me please..

**Comment by rossp** [comment]
You probably need to change your "Base URL" to just "/"... as you can see from the code you've posted, comparison is done on `request.path` to determine which submenu to display. `request.path` just contains a relative path, ie `/` or `/about/`.

**Comment by karina-klinkeviciute** [comment]
As I understood, the submenu is for showing specific menus in some pages, not for, for example, 
dropdown functionality?
Is there a way to get the dropdown functionality easily so that I wouldn't need to manually add a menu for each main menu item?

**Comment by rossp** [comment]
Yes, the submenu is used for menus within a given path. The presentation on your page (ie as a dropdown or otherwise) is outside the scope of this project and is entirely up to you.

**Comment by karina-klinkeviciute** [comment]
Probably I didn't express myself clearly.
As I understand, the submenu for the /about/ would be showing only in about page, and submenu in /company/ would be showing only in o/company/ page?
It's not meant to produce a structured menu, like this for example:
  
about                    company
  about1                  company 1
  about 2                 company2

Or is it?

**Comment by rossp** [comment]
That's right, your "about" submenu has a base url of /about/, and your menu items have URLs of eg /about/1, /about/2, /about/3. On pages within /about/, this submenu will be shown.

**Comment by karina-klinkeviciute** [comment]
Thanks for clarification :)
