### ISSUE TITLE
Error in Django 1.10 south

### ISSUE THREAD

**Issue by CARocha** [rossp/django-menu#20]
Hi i use Django 1.10.x when install i see the error
from south.db import db
ImportError: No module named south.db

i know i need install south but why Django core have migration app, i think need update
the code for use in Django 1.7+ this version no need anymore south.

Thank

**Comment by rossp** [comment]
Since Django 1.7 South is no longer required, however this project is outdated and needs updates to the migrations - and probably elsewhere - to support more recent versions of Django.

PRs welcome :)

**Comment by rossp** [comment]
Upon review, the code is up to date for migrations but the PyPi package is outdated.  I'll dig into it when time permits.
